apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react
spec:
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: localhost:5000/react:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 3000
        resources:
          limits:
            memory: 512Mi
